report:
  variables:
    urls:
      #      report: localhost:8080
      redis:
        topic: "report"

server:
  port: 9091

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    port: "${REDIS_PORT}"
    host: "${REDIS_HOST}"
    password: "${REDIS_PASSWORD}"



  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
  datasource:
    url: "jdbc:postgresql://localhost:5432/trading"
    username: broker
    password: rouge_broker
  flyway:
    schemas: trading
#  jpa:
#    properties:



